### PR TITLE
fix!: enable some jsx-a11y rules

### PR DESCRIPTION
**Pull request by blindsoup**
Added / modified some rules.
Deleted jsx-a11y/img-redundant-alt options.
About "components", it is desirable to set "components" in individual projects.
About "words", it Does not support Japanese.

### CODE REVIEW

**Review by koba04 — APPROVED** [review]
👍 👍 👍 Thank you!

**Comment by koba04** [comment]
@blindsoup
Could you fix the lint error?
You could fix the errors by the `npm run lint -- --fix` command.

**Review by sakito21 — APPROVED** [review]

**Comment by blindsoup** [comment]
@koba04 I'm sorry to be late. I applied a lint. Please confirm.

**Comment by koba04** [comment]
@blindsoup Thank you for your great works! 👏

**Pull request merged**
